version: '3.3'

services:

  # Serviço de paginas NGINX
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/sites/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
      - MYSQL_ROOT_PASSWORD=123456
    env_file:
      - .env

  # Serviço PHP-fpm
  php-fpm:
    container_name: php-fpm
    restart: always
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    expose:
      - "9000"    
    volumes:
      - ./app:/var/www/html
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    env_file:
      - .env
      - .env_mysql

  # Serviço MySQL 5.7
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql-db-data:/var/lib/mysql
    env_file:
      - .env
      - .env_mysql

volumes:
  mysql-db-data: